[build]
  base = "/"
  publish = "dist/"

[build.environment]
  YARN_VERSION = "1.12.3"
  NODE_VERSION = "14"

[context.production]
  command = "sh .netlify/scripts/deploy-prod.sh"

[context.deploy-preview]
  command = "sh .netlify/scripts/deploy-dev.sh"

[context.branch-deploy]
  command = "sh .netlify/scripts/deploy-dev.sh"