query getPageGallery($id: ID!) {
  PagegalleryItem(id: $id) {
    content {
      title
      subtitle
      photographer
      date
      images {
        filename
        name
      }
      meta
    }
  }
}
